import os

SCENARIOS = {
    "quests": {
        "01": {"name": "The Sandstone Secret", "tier_min": 1, "tier_max": 4},
        "02": {"name": "Unforgiving Fire", "tier_min": 1, "tier_max": 4},
        "03": {"name": "Grehunde’s Gorget", "tier_min": 1, "tier_max": 4},
        "04": {"name": "Port Peril Pub Crawl", "tier_min": 1, "tier_max": 4},
        "05": {"name": "The Dragon Who Stole Evoking Day", "tier_min": 3, "tier_max": 6},
        "06": {"name": "Archaeology in Aspenthar", "tier_min": 1, "tier_max": 4},
        "07": {"name": "A Curious Claim", "tier_min": 3, "tier_max": 6},
        "08": {"name": "Shadows of the Black Sovereign", "tier_min": 3, "tier_max": 6},
        "09": {"name": "Wayfinder Origins", "tier_min": 3, "tier_max": 6},
        "10": {"name": "The Broken Scales", "tier_min": 1, "tier_max": 4},
        "11": {"name": "A Parchment Tree", "tier_min": 1, "tier_max": 4},
        "12": {"name": "Putrid Seeds", "tier_min": 3, "tier_max": 6},
        "13": {"name": "Falcon’s Descent", "tier_min": 1, "tier_max": 4},
        "14": {"name": "The Swordlord's Challenge", "tier_min": 1, "tier_max": 4},
        "15": {"name": "In the Footsteps of Horror", "tier_min": 1, "tier_max": 4},
        "16": {"name": "The Winter Queen's Dollhouse", "tier_min": 1, "tier_max": 4},
        "17": {"name": "Escorting a Mirage", "tier_min": 1, "tier_max": 4},
        "18": {"name": "Student Exchange", "tier_min": 1, "tier_max": 4},
        "19": {"name": "The Elsewhere Feast", "tier_min": 1, "tier_max": 4},
        "20": {"name": "The Dacilane's Academy's Show Must Go On", "tier_min": 1, "tier_max": 4},
        "21": {"name": "Infernal Infiltration", "tier_min": 1, "tier_max": 4},
        "22": {"name": "Friends in Need", "tier_min": 1, "tier_max": 4},
        "23": {"name": "Lacking Respect", "tier_min": 1, "tier_max": 4},
        "24": {"name": "Tanuki Trouble", "tier_min": 1, "tier_max": 4}
    },
    "season_1": {
        "00": {"name": "Origin of the Open Road", "tier_min": 5, "tier_max": 5},
        "01": {"name": "The Absalom Initiation", "tier_min": 1, "tier_max": 4},
        "02": {"name": "The Mosquito Witch", "tier_min": 1, "tier_max": 4},
        "03": {"name": "Escaping the Grave", "tier_min": 1, "tier_max": 4},
        "04": {"name": "Bandits of Immenwood", "tier_min": 1, "tier_max": 4},
        "05": {"name": "Trailblazer's Bounty", "tier_min": 1, "tier_max": 4},
        "06": {"name": "Lost on the Spirit Road", "tier_min": 1, "tier_max": 4},
        "07": {"name": "Flooded King’s Court", "tier_min": 1, "tier_max": 4},
        "08": {"name": "Revolution on the Riverside", "tier_min": 1, "tier_max": 4},
        "09": {"name": "Star-Crossed Voyages", "tier_min": 3, "tier_max": 6},
        "10": {"name": "Tarnbreaker’s Trail", "tier_min": 1, "tier_max": 4},
        "11": {"name": "Flames of Rebellion", "tier_min": 1, "tier_max": 4},
        "12": {"name": "Burden of Envy", "tier_min": 1, "tier_max": 4},
        "13": {"name": "Devil at the Crossroads", "tier_min": 3, "tier_max": 6},
        "14": {"name": "Lions of Katapesh", "tier_min": 1, "tier_max": 4},
        "15": {"name": "The Blooming Catastrophe", "tier_min": 1, "tier_max": 4},
        "16": {"name": "The Perennial Crown Part 1: Opal of Bhopan", "tier_min": 3, "tier_max": 6},
        "17": {"name": "The Perennial Crown Part 2: The Thorned Monarch", "tier_min": 3, "tier_max": 6},
        "18": {"name": "Lodge of the Living God", "tier_min": 1, "tier_max": 4},
        "19": {"name": "Iolite Squad Alpha", "tier_min": 3, "tier_max": 6},
        "20": {"name": "The Lost Legend", "tier_min": 3, "tier_max": 6},
        "21": {"name": "Mistress of the Maze", "tier_min": 5, "tier_max": 8},
        "22": {"name": "Doom of Cassomir", "tier_min": 1, "tier_max": 4},
        "23": {"name": "Star-Crossed Court", "tier_min": 3, "tier_max": 6},
        "24": {"name": "Lightning Strikes, Stars Fall", "tier_min": 5, "tier_max": 8},
        "25": {"name": "Grim Symphony", "tier_min": 5, "tier_max": 8}
    },
    "season_2": {
        "00.1": {"name": "King in Thorns", "tier_min": 1, "tier_max": 2},
        "00.2": {"name": "King in Thorns", "tier_min": 3, "tier_max": 6},
        "00.3": {"name": "King in Thorns", "tier_min": 7, "tier_max": 8},
        "01": {"name": "Citadel of Corruption", "tier_min": 1, "tier_max": 4},
        "02": {"name": "Mountain of Sea and Sky", "tier_min": 3, "tier_max": 6},
        "03": {"name": "Catastrophe’s Spark", "tier_min": 1, "tier_max": 4},
        "04": {"name": "Path of Kings", "tier_min": 3, "tier_max": 6},
        "05": {"name": "Balancing the Scales", "tier_min": 1, "tier_max": 4},
        "06": {"name": "The Crashing Wave", "tier_min": 3, "tier_max": 6},
        "07": {"name": "The Blakros Deception", "tier_min": 5, "tier_max": 8},
        "08": {"name": "A Frosty Mug", "tier_min": 5, "tier_max": 8},
        "09": {"name": "The Seven Secrets of Dacilane Academy", "tier_min": 1, "tier_max": 4},
        "10": {"name": "In Burning Dawn", "tier_min": 5, "tier_max": 8},
        "11": {"name": "The Pathfinder Trials", "tier_min": 1, "tier_max": 1},
        "12": {"name": "Snakes in the Grass", "tier_min": 3, "tier_max": 6},
        "13": {"name": "A Gilded Test", "tier_min": 1, "tier_max": 4},
        "14": {"name": "Lost in Flames", "tier_min": 3, "tier_max": 6},
        "15": {"name": "A Dirge for Sarkoris", "tier_min": 3, "tier_max": 6},
        "16": {"name": "Freedom for Wishes", "tier_min": 5, "tier_max": 8},
        "17": {"name": "Lost Maid of Anactoria", "tier_min": 3, "tier_max": 6},
        "18": {"name": "The Fanciful March of Urwal", "tier_min": 3, "tier_max": 6},
        "19": {"name": "Enter the Pallid Peak", "tier_min": 1, "tier_max": 4},
        "20": {"name": "Breaking the Storm: Bastion in Embers", "tier_min": 5, "tier_max": 8},
        "21": {"name": "In Pursuit of Water", "tier_min": 1, "tier_max": 4},
        "22": {"name": "Breaking the Storm: Excising Ruination", "tier_min": 7, "tier_max": 10},
        "23": {"name": "An Agent’s Obligation", "tier_min": 3, "tier_max": 6},
        "24": {"name": "Breaking the Storm: Parting Clouds", "tier_min": 7, "tier_max": 10}
    },
    "season_3": {
        "01": {"name": "Intro: Year of Shattered Sanctuaries", "tier_min": 1, "tier_max": 4},
        "02": {"name": "The East Hill Haunting", "tier_min": 1, "tier_max": 4},
        "03": {"name": "Echoes of Desperation", "tier_min": 3, "tier_max": 6},
        "04": {"name": "The Devil-Wrought Disappearance", "tier_min": 3, "tier_max": 6},
        "05": {"name": "Inheritor’s Rite", "tier_min": 1, "tier_max": 4},
        "06": {"name": "Struck by Shadows", "tier_min": 3, "tier_max": 6},
        "07": {"name": "The Locked Lodge", "tier_min": 3, "tier_max": 6},
        "08": {"name": "Foundation's Price", "tier_min": 1, "tier_max": 4},
        "09": {"name": "The Secluded Siege", "tier_min": 5, "tier_max": 8},
        "10": {"name": "Delve the Pallid Depths", "tier_min": 1, "tier_max": 4},
        "11": {"name": "No Time for Treason", "tier_min": 3, "tier_max": 6},
        "12": {"name": "Fury's Toll", "tier_min": 1, "tier_max": 4},
        "13": {"name": "Guardian's Covenant", "tier_min": 3, "tier_max": 6},
        "14": {"name": "The Tomb Between Worlds", "tier_min": 5, "tier_max": 8},
        "15": {"name": "Cavern of the Sundered Song", "tier_min": 9, "tier_max": 12},
        "16": {"name": "Escape from Oppara", "tier_min": 3, "tier_max": 6},
        "17": {"name": "Dreams of a Dustbound Isle", "tier_min": 5, "tier_max": 8},
        "18": {"name": "Dacilane Academy's Delightful Disaster", "tier_min": 1, "tier_max": 4},
        "19": {"name": "Mean Streets of Shadow Absalom", "tier_min": 7, "tier_max": 10},
        "98.1": {"name": "Expedition into Pallid Peril", "tier_min": 1, "tier_max": 4},
        "98.2": {"name": "Expedition into Pallid Peril", "tier_min": 3, "tier_max": 6},
        "99.1": {"name": "Fate in the Future", "tier_min": 1, "tier_max": 4},
        "99.2": {"name": "Fate in the Future", "tier_min": 5, "tier_max": 8}
    },
    "season_4": {
        "01": {"name": "Intro: Year of Boundless Wonder", "tier_min": 1, "tier_max": 4},
        "02": {"name": "Return to the Grave", "tier_min": 1, "tier_max": 4},
        "03": {"name": "Linnorm’s Legacy", "tier_min": 5, "tier_max": 8},
        "04": {"name": "To Seek the Heart of Calamity", "tier_min": 3, "tier_max": 6},
        "05": {"name": "The Arclord Who Never Was", "tier_min": 1, "tier_max": 4},
        "06": {"name": "Signal from the Electric Laboratory", "tier_min": 7, "tier_max": 10},
        "07": {"name": "A Most Wondrous Exchange!", "tier_min": 5, "tier_max": 8},
        "08": {"name": "Battle for Star’s Fate", "tier_min": 3, "tier_max": 6},
        "09": {"name": "Killer in the Golden Mask", "tier_min": 5, "tier_max": 8},
        "10": {"name": "Arclord’s Abode", "tier_min": 1, "tier_max": 4},
        "11": {"name": "Prisoners of the Electric Castle", "tier_min": 7, "tier_max": 10},
        "12": {"name": "Negotiations for the Star Gun", "tier_min": 1, "tier_max": 4},
        "13": {"name": "Within the Prairies", "tier_min": 1, "tier_max": 4},
        "14": {"name": "Shattering Golden Chains", "tier_min": 3, "tier_max": 6},
        "15": {"name": "In Glorious Battle", "tier_min": 9, "tier_max": 12},
        "16": {"name": "Dacilane Academy’s First Great Prank War", "tier_min": 3, "tier_max": 6},
        "17": {"name": "Trapping the Hag’s Claw", "tier_min": 7, "tier_max": 10}
    },
    "season_5": {
        "01": {"name": "Intro: Year of Unfettered Exploration", "tier_min": 1, "tier_max": 4},
        "02": {"name": "The Blackwood Lost", "tier_min": 3, "tier_max": 6},
        "03": {"name": "Heidmarch Heist", "tier_min": 5, "tier_max": 8},
        "04": {"name": "Equal Exchanges - Necessary Introductions", "tier_min": 1, "tier_max": 4},
        "05": {"name": "The Island of the Vibrant Dead", "tier_min": 3, "tier_max": 6},
        "06": {"name": "Ukuja, The First Wall", "tier_min": 7, "tier_max": 10},
        "07": {"name": "Sewer Dragon Crisis", "tier_min": 1, "tier_max": 4},
        "08": {"name": "Protecting the Firelight", "tier_min": 5, "tier_max": 8},
        "09": {"name": "Equal Exchanges – Skymetal Hoard", "tier_min": 5, "tier_max": 8},
        "10": {"name": "The Crocodile's Smile", "tier_min": 1, "tier_max": 4},
        "11": {"name": "Equal Exchanges - The Hidden Current", "tier_min": 7, "tier_max": 10},
        "12": {"name": "Mischief in the Maze", "tier_min": 1, "tier_max": 4},
        "13": {"name": "Thick as Thieves", "tier_min": 5, "tier_max": 8},
        "14": {"name": "Poisonous Council", "tier_min": 3, "tier_max": 6},
        "15": {"name": "Cleansing the Flame", "tier_min": 5, "tier_max": 8},
        "16": {"name": "A Lie told to Strangers", "tier_min": 3, "tier_max": 6},
        "17": {"name": "Stranded on Yesterday’S Tide", "tier_min": 1, "tier_max": 4},
        "18": {"name": "Tapestry of the Mind", "tier_min": 9, "tier_max": 12},
        "19": {"name": "Demonic Afterparty", "tier_min": 3, "tier_max": 6},
        "20": {"name": "The Rakshasa’s Court", "tier_min": 7, "tier_max": 10}
    },
    "season_6": {
        "00": {"name": "Salt of the Ocean", "tier_min": 1, "tier_max": 8},
        "01": {"name": "Intro to the Year of Immortal Influence", "tier_min": 1, "tier_max": 4},
        "02": {"name": "Rain Falls on the Mountain of Sea and Sky", "tier_min": 1, "tier_max": 4},
        "03": {"name": "Godsrain in a Godless Land", "tier_min": 5, "tier_max": 8},
        "04": {"name": "An Enkindled Carnival", "tier_min": 3, "tier_max": 6},
        "05": {"name": "Silver Bark, Golden Blades", "tier_min": 1, "tier_max": 4},
        "06": {"name": "Rotten Apples", "tier_min": 3, "tier_max": 6},
        "07": {"name": "A God Falls Where Magic Fails", "tier_min": 7, "tier_max": 10},
        "08": {"name": "Upon Wheels and Rime", "tier_min": 1, "tier_max": 4},
        "09": {"name": "The Power of Legends", "tier_min": 9, "tier_max": 12},
        "10": {"name": "Once in Whispers", "tier_min": 5, "tier_max": 8},
        "11": {"name": "The Godsrain and the Dragon", "tier_min": 7, "tier_max": 10},
        "12": {"name": "The Burning of Greensteeples", "tier_min": 3, "tier_max": 6},
        "13": {"name": "All That Glitters", "tier_min": 1, "tier_max": 4},
        "14": {"name": "Twice in Steel", "tier_min": 7, "tier_max": 10},
        "15": {"name": "Lost and Forgotten", "tier_min": 5, "tier_max": 8},
        "16": {"name": "The Heart of the City", "tier_min": 5, "tier_max": 8},
        "17": {"name": "The Devil in the Details", "tier_min": 7, "tier_max": 10},
        "18": {"name": "Symposium on a Fallen God", "tier_min": 3, "tier_max": 6},
        "19": {"name": "What Walks Again", "tier_min": 11, "tier_max": 14},
        "20": {"name": "The Overthrow of Ambition", "tier_min": 9, "tier_max": 12}
    },
    "season_7": {
        "01": {"name": "Enough is Enough", "tier_min": 1, "tier_max": 4},
        "02": {"name": "Shipyard Sabotage", "tier_min": 1, "tier_max": 4},
        "03": {"name": "A Foot in the Door", "tier_min": 5, "tier_max": 8},
        "04": {"name": "Sulfuric Negotiations", "tier_min": 3, "tier_max": 6},
        "05": {"name": "Battle of the Thorns", "tier_min": 9, "tier_max": 12},
        "06": {"name": "Brastlewark at War Part 1: The Gnome Defection", "tier_min": 1, "tier_max": 4},
        "07": {"name": "Draconic Folly", "tier_min": 7, "tier_max": 10},
        "08": {"name": "The Haunted Corridor", "tier_min": 1, "tier_max": 4},
        "09": {"name": "The Chitterwood Walks, Part 1: Scrambling the Tribes", "tier_min": 3, "tier_max": 4},
        "10": {"name": "Shattered Blades", "tier_min": 13, "tier_max": 14},
        "11": {"name": "The Darkness Within", "tier_min": 7, "tier_max": 8},
        "12": {"name": "The Chitterwood Walks, Part 2: The Battle of Logas", "tier_min": 5, "tier_max": 6},
        "13": {"name": "Ancient Beyond Imagining", "tier_min": 9, "tier_max": 10},
        "14": {"name": "Brastlewark at War, Part 2: The Gnome Liberation", "tier_min": 4, "tier_max": 4},
        "15": {"name": "Within Antiquated Halls", "tier_min": 7, "tier_max": 8},
        "16": {"name": "A Star’s Journey", "tier_min": 1, "tier_max": 2},
        "17": {"name": "Perch of Liberty", "tier_min": 3, "tier_max": 4},
        "18": {"name": "Freedom on the Sea", "tier_min": 5, "tier_max": 6},
        "19": {"name": "The Lost Legacy", "tier_min": 7, "tier_max": 8},
        "20": {"name": "The Strings of Hell", "tier_min": 1, "tier_max": 2}
    },
    "season_8": {

    }
}

# Add a special "developer_mode" season and scenario if the DEVELOPER_MODE environment variable is set to "true"
if os.environ.get("DEVELOPER_MODE", "false").lower() == "true":
    SCENARIOS["developer_mode"] = {
        "test_scenario": {"name": "Developer Test Scenario", "tier_min": 1, "tier_max": 10}
    }


if __name__ == "__main__":
    print(SCENARIOS["quests"]["01"])
    # Example of how to check the developer mode scenario
    if "developer_mode" in SCENARIOS:
        print("\nDeveloper Mode is ON. Test Scenario:")
        print(SCENARIOS["developer_mode"]["test_scenario"])